import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "I-Tech Komputer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        {/* <title>Bootshop online Shopping cart</title> */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <link id="callCss" rel="stylesheet" href="template/themes/bootshop/bootstrap.min.css" media="screen"/>
        <link href="template/themes/css/base.css" rel="stylesheet" media="screen" />
        <link href="template/themes/css/bootstrap-responsive.min.css" rel="stylesheet" />
        <link href="template/themes/css/font-awesome.css" rel="stylesheet" type="text/css" />
        <link href="template/themes/js/google-code-prettify/prettify.css" rel="stylesheet" />
        <link rel="shortcut icon" href="template/themes/images/ico/favico.png" />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="144x144"
          href="themes/images/ico/apple-touch-icon-144-precomposed.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="114x114"
          href="themes/images/ico/apple-touch-icon-114-precomposed.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          sizes="72x72"
          href="themes/images/ico/apple-touch-icon-72-precomposed.png"
        />
        <link
          rel="apple-touch-icon-precomposed"
          href="themes/images/ico/apple-touch-icon-57-precomposed.png"
        />
        <style type="text/css" id="enject" dangerouslySetInnerHTML={{ __html: "" }} />
      </head>

      <body>{children}</body>
    </html>
  );
}
